export const contactType = {
  SET_LIST_CONTACT: 'SET_LIST_CONTACT',
  SET_LOADING: 'SET_LOADING',
  SET_FIRSTNAME: 'SET_FIRSTNAME',
  SET_LASTNAME: 'SET_LASTNAME',
  SET_AGE: 'SET_AGE',
  SET_PHOTO: 'SET_PHOTO',
  SET_ID_CONTACT: 'SET_ID_CONTACT',
};